# Generated by Django 3.2.17 on 2023-11-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_dweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dweet',
            old_name='dweet',
            new_name='body',
        ),
    ]
