# Generated by Django 3.2.17 on 2023-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_rename_dweet_dweet_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='num_of_edit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
