# Generated by Django 3.2.17 on 2023-11-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_dweet_num_of_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='num_of_edit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
